version: "3.8"

services:
    app:
        image: ghcr.io/dekarlo/ghcr.io/dekarlo/srefinal:refs_heads_main
        build: .
        volumes:
            - .:/app
        command: ["python3", "main.py"]
        restart: always
        depends_on:
            - pushgateway

    pushgateway:
        image: prom/pushgateway:latest
        ports:
            - "9091:9091"
        restart: always